version: '3.8'

services:
  # --- BACKEND ---
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: faceid_backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
      - ../data:/app/data
      - ../backend/weights:/app/weights
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}  
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - faceid_network

  # --- FRONTEND (NODEJS) ---
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: faceid_node_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=3000

    env_file:
      - ../.env 

    depends_on:
      - db
    volumes:
      - ../frontend:/app
      - /app/node_modules
    
    networks:
      - faceid_network

  # --- DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: faceid_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - faceid_network

volumes:
  postgres_data:

networks:
  faceid_network:
    driver: bridge